In [1]:
import numpy as np
import pandas as pd

data = pd.read_csv('/Users/HuanYe/Desktop/Project2_DS504/data/data.csv')
data

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RateCodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,2,2015-01-15 19:05:39,2015-01-15 19:23:42,1,1.59,-73.993896,40.750111,1,N,-73.974785,40.750618,1,12.0,1.0,0.5,3.25,0.00,0.3,17.05
1,1,2015-01-10 20:33:38,2015-01-10 20:53:28,1,3.30,-74.001648,40.724243,1,N,-73.994415,40.759109,1,14.5,0.5,0.5,2.00,0.00,0.3,17.80
2,1,2015-01-10 20:33:38,2015-01-10 20:43:41,1,1.80,-73.963341,40.802788,1,N,-73.951820,40.824413,2,9.5,0.5,0.5,0.00,0.00,0.3,10.80
3,1,2015-01-10 20:33:39,2015-01-10 20:35:31,1,0.50,-74.009087,40.713818,1,N,-74.004326,40.719986,2,3.5,0.5,0.5,0.00,0.00,0.3,4.80
4,1,2015-01-10 20:33:39,2015-01-10 20:52:58,1,3.00,-73.971176,40.762428,1,N,-74.004181,40.742653,2,15.0,0.5,0.5,0.00,0.00,0.3,16.30
5,1,2015-01-10 20:33:39,2015-01-10 20:53:52,1,9.00,-73.874374,40.774048,1,N,-73.986977,40.758194,1,27.0,0.5,0.5,6.70,5.33,0.3,40.33
6,1,2015-01-10 20:33:39,2015-01-10 20:58:31,1,2.20,-73.983276,40.726009,1,N,-73.992470,40.749634,2,14.0,0.5,0.5,0.00,0.00,0.3,15.30
7,1,2015-01-10 20:33:39,2015-01-10 20:42:20,3,0.80,-74.002663,40.734142,1,N,-73.995010,40.726326,1,7.0,0.5,0.5,1.66,0.00,0.3,9.96
8,1,2015-01-10 20:33:39,2015-01-10 21:11:35,3,18.20,-73.783043,40.644356,2,N,-73.987595,40.759357,2,52.0,0.0,0.5,0.00,5.33,0.3,58.13
9,1,2015-01-10 20:33:40,2015-01-10 20:40:44,2,0.90,-73.985588,40.767948,1,N,-73.985916,40.759365,1,6.5,0.5,0.5,1.55,0.00,0.3,9.35
10,1,2015-01-10 20:33:40,2015-01-10 20:41:39,1,0.90,-73.988617,40.723103,1,N,-74.004395,40.728584,1,7.0,0.5,0.5,1.66,0.00,0.3,9.96
11,1,2015-01-10 20:33:41,2015-01-10 20:43:26,1,1.10,-73.993782,40.751419,1,N,-73.967407,40.757217,1,7.5,0.5,0.5,1.00,0.00,0.3,9.80
12,1,2015-01-10 20:33:41,2015-01-10 20:35:23,1,0.30,-74.008362,40.704376,1,N,-74.009773,40.707726,2,3.0,0.5,0.5,0.00,0.00,0.3,4.30
13,1,2015-01-10 20:33:41,2015-01-10 21:03:04,1,3.10,-73.973946,40.760448,1,N,-73.997345,40.735210,1,19.0,0.5,0.5,3.00,0.00,0.3,23.30
14,1,2015-01-10 20:33:41,2015-01-10 20:39:23,1,1.10,-74.006721,40.731777,1,N,-73.995216,40.739895,2,6.0,0.5,0.5,0.00,0.00,0.3,7.30
15,2,2015-01-15 19:05:39,2015-01-15 19:32:00,1,2.38,-73.976425,40.739811,1,N,-73.983978,40.757889,1,16.5,1.0,0.5,4.38,0.00,0.3,22.68
16,2,2015-01-15 19:05:40,2015-01-15 19:21:00,5,2.83,-73.968704,40.754246,1,N,-73.955124,40.786858,2,12.5,1.0,0.5,0.00,0.00,0.3,14.30
17,2,2015-01-15 19:05:40,2015-01-15 19:28:18,5,8.33,-73.863060,40.769581,1,N,-73.952713,40.785782,1,26.0,1.0,0.5,8.08,5.33,0.3,41.21
18,2,2015-01-15 19:05:41,2015-01-15 19:20:36,1,2.37,-73.945541,40.779423,1,N,-73.980850,40.786083,1,11.5,1.0,0.5,0.00,0.00,0.3,13.30
19,2,2015-01-15 19:05:41,2015-01-15 19:20:22,2,7.13,-73.874458,40.774010,1,N,-73.952377,40.718590,1,21.5,1.0,0.5,4.50,0.00,0.3,27.80
20,2,2015-01-15 19:05:41,2015-01-15 19:31:00,1,3.60,-73.976601,40.751896,1,N,-73.998924,40.714596,2,17.5,1.0,0.5,0.00,0.00,0.3,19.30
21,2,2015-01-15 19:05:41,2015-01-15 19:10:22,1,0.89,-73.994957,40.745079,1,N,-73.999939,40.734650,1,5.5,1.0,0.5,1.62,0.00,0.3,8.92
22,2,2015-01-15 19:05:41,2015-01-15 19:10:55,1,0.96,-74.000938,40.747063,1,N,-74.003563,40.735512,1,5.5,1.0,0.5,1.30,0.00,0.3,8.60
23,2,2015-01-15 19:05:41,2015-01-15 19:12:36,2,1.25,-74.002777,40.717892,1,N,-74.007919,40.704220,1,6.5,1.0,0.5,1.50,0.00,0.3,9.80
24,2,2015-01-15 19:05:41,2015-01-15 19:22:11,5,2.11,-73.997459,40.736362,1,N,-73.978172,40.761856,1,11.5,1.0,0.5,2.50,0.00,0.3,15.80
25,2,2015-01-15 19:05:41,2015-01-15 19:14:05,5,1.15,-73.952278,40.823994,1,N,-73.953339,40.811089,1,7.5,1.0,0.5,1.70,0.00,0.3,11.00
26,2,2015-01-15 19:05:42,2015-01-15 19:16:18,1,1.53,-73.991127,40.750080,1,N,-73.988609,40.734890,2,9.0,1.0,0.5,0.00,0.00,0.3,10.80
27,2,2015-01-15 19:05:42,2015-01-15 19:49:07,1,18.06,-73.786575,40.644127,2,N,-73.985603,40.743530,1,52.0,0.0,0.5,6.00,5.33,0.3,64.13
28,2,2015-01-15 19:05:42,2015-01-15 19:18:33,1,1.76,-73.993668,40.741447,1,N,-73.994514,40.757721,1,10.0,1.0,0.5,2.36,0.00,0.3,14.16
29,2,2015-01-15 19:05:42,2015-01-15 19:21:40,6,5.19,-73.985291,40.744083,1,N,-74.009079,40.704689,1,17.5,1.0,0.5,3.70,0.00,0.3,23.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12748956,2,2015-01-23 12:27:15,2015-01-23 12:38:06,6,1.36,-73.958443,40.778362,1,N,-73.969795,40.764603,2,8.5,0.0,0.5,0.00,0.00,0.3,9.30
12748957,2,2015-01-23 12:27:15,2015-01-23 12:53:56,6,2.36,-73.987335,40.768406,1,N,-73.998055,40.740685,2,17.0,0.0,0.5,0.00,0.00,0.3,17.80
12748958,2,2015-01-23 12:27:15,2015-01-23 12:41:25,5,3.88,-73.954872,40.765572,1,N,-73.931190,40.767963,2,14.5,0.0,0.5,0.00,0.00,0.3,15.30
12748959,2,2015-01-23 12:27:15,2015-01-23 12:43:09,6,1.69,-73.980652,40.759396,1,N,-73.992538,40.749332,1,11.5,0.0,0.5,2.46,0.00,0.3,14.76
12748960,2,2015-01-23 12:27:16,2015-01-23 12:31:29,1,0.72,-73.992844,40.733875,1,N,-73.997375,40.727638,2,5.0,0.0,0.5,0.00,0.00,0.3,5.80
12748961,2,2015-01-23 12:27:16,2015-01-23 12:37:22,1,1.42,-73.983971,40.749336,1,N,-73.986771,40.733913,2,8.5,0.0,0.5,0.00,0.00,0.3,9.30
12748962,2,2015-01-23 12:27:17,2015-01-23 12:43:49,5,2.62,-73.990837,40.759426,1,N,-73.977943,40.789776,1,12.5,0.0,0.5,1.50,0.00,0.3,14.80
12748963,2,2015-01-23 12:27:17,2015-01-23 12:40:50,2,2.86,-73.984108,40.780148,1,N,-73.956154,40.807259,1,12.0,0.0,0.5,2.56,0.00,0.3,15.36
12748964,1,2015-01-10 19:01:40,2015-01-10 19:13:29,2,1.00,-74.006248,40.741375,1,N,-73.991386,40.738457,2,8.5,0.0,0.5,0.00,0.00,0.3,9.30
12748965,1,2015-01-10 19:01:40,2015-01-10 19:20:34,1,3.50,-73.950005,40.772049,1,N,-73.991814,40.759243,2,15.0,0.0,0.5,0.00,0.00,0.3,15.80
12748966,1,2015-01-10 19:01:41,2015-01-10 19:21:17,2,4.30,-73.952354,40.769779,1,N,-73.990189,40.730953,1,17.5,0.0,0.5,3.65,0.00,0.3,21.95
12748967,1,2015-01-10 19:01:41,2015-01-10 19:09:25,2,3.00,-74.000916,40.762001,1,N,-73.971794,40.797024,2,11.0,0.0,0.5,0.00,0.00,0.3,11.80
12748968,1,2015-01-10 19:01:41,2015-01-10 19:09:15,2,1.00,-73.976318,40.765816,1,N,-73.987381,40.775139,2,7.0,0.0,0.5,0.00,0.00,0.3,7.80
12748969,1,2015-01-10 19:01:41,2015-01-10 19:13:42,2,1.90,-73.956383,40.767124,1,N,-73.982300,40.768372,1,10.0,0.0,0.5,2.16,0.00,0.3,12.96
12748970,1,2015-01-10 19:01:41,2015-01-10 19:12:25,1,0.80,-73.984947,40.728088,1,N,-73.993469,40.727413,2,8.0,0.0,0.5,0.00,0.00,0.3,8.80
12748971,1,2015-01-10 19:01:42,2015-01-10 19:08:10,1,0.70,-73.993622,40.728634,1,N,-74.000839,40.721409,1,5.5,0.0,0.5,1.25,0.00,0.3,7.55
12748972,1,2015-01-10 19:01:42,2015-01-10 19:15:38,1,2.30,-73.964211,40.767441,1,N,-73.992050,40.755951,1,11.5,0.0,0.5,2.45,0.00,0.3,14.75
12748973,1,2015-01-10 19:01:42,2015-01-10 19:11:56,1,1.60,-73.979729,40.763844,1,N,-73.990929,40.746349,1,8.5,0.0,0.5,1.00,0.00,0.3,10.30
12748974,1,2015-01-10 19:01:43,2015-01-10 19:15:22,1,2.00,-73.993729,40.758690,1,N,-73.998039,40.736324,1,10.5,0.0,0.5,3.00,0.00,0.3,14.30
12748975,1,2015-01-10 19:01:43,2015-01-10 19:13:15,2,1.80,-73.989044,40.730389,1,N,-73.971138,40.748104,1,9.0,0.0,0.5,1.95,0.00,0.3,11.75
12748976,1,2015-01-10 19:01:43,2015-01-10 19:14:04,1,1.90,-73.981789,40.765335,1,N,-73.980782,40.744892,1,9.5,0.0,0.5,1.50,0.00,0.3,11.80
12748977,1,2015-01-10 19:01:43,2015-01-10 19:23:48,1,4.50,-73.951477,40.785252,1,N,-73.996536,40.738205,1,18.5,0.0,0.5,3.85,0.00,0.3,23.15
12748978,1,2015-01-10 19:01:43,2015-01-10 19:12:05,1,1.60,-73.984421,40.748260,1,N,-73.989220,40.730583,1,8.5,0.0,0.5,2.30,0.00,0.3,11.60
12748979,1,2015-01-10 19:01:43,2015-01-10 19:27:13,1,2.30,-73.994240,40.750805,1,N,-73.988686,40.730900,2,16.5,0.0,0.5,0.00,0.00,0.3,17.30
12748980,1,2015-01-10 19:01:44,2015-01-10 19:20:09,1,2.10,-73.980827,40.744530,1,N,-74.008873,40.740929,1,13.0,0.0,0.5,1.50,0.00,0.3,15.30
12748981,1,2015-01-10 19:01:44,2015-01-10 19:05:40,2,1.00,-73.951988,40.786217,1,N,-73.953735,40.775162,1,5.5,0.0,0.5,1.25,0.00,0.3,7.55
12748982,1,2015-01-10 19:01:44,2015-01-10 19:07:26,2,0.80,-73.982742,40.728184,1,N,-73.974976,40.720013,1,6.0,0.0,0.5,2.00,0.00,0.3,8.80
12748983,1,2015-01-10 19:01:44,2015-01-10 19:15:01,1,3.40,-73.979324,40.749550,1,N,-73.969101,40.787800,2,13.5,0.0,0.5,0.00,0.00,0.3,14.30
12748984,1,2015-01-10 19:01:44,2015-01-10 19:17:03,1,1.30,-73.999565,40.738483,1,N,-73.981819,40.737652,1,10.5,0.0,0.5,2.25,0.00,0.3,13.55
12748985,1,2015-01-10 19:01:45,2015-01-10 19:07:33,1,0.70,-73.960350,40.766399,1,N,-73.968643,40.760777,2,5.5,0.0,0.5,0.00,0.00,0.3,6.30

In [2]:
important_features=['tpep_pickup_datetime','pickup_longitude','pickup_latitude','dropoff_longitude','dropoff_latitude']
important_data= data.loc[:,important_features]
important_data

,tpep_pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude
0,2015-01-15 19:05:39,-73.993896,40.750111,-73.974785,40.750618
1,2015-01-10 20:33:38,-74.001648,40.724243,-73.994415,40.759109
2,2015-01-10 20:33:38,-73.963341,40.802788,-73.951820,40.824413
3,2015-01-10 20:33:39,-74.009087,40.713818,-74.004326,40.719986
4,2015-01-10 20:33:39,-73.971176,40.762428,-74.004181,40.742653
5,2015-01-10 20:33:39,-73.874374,40.774048,-73.986977,40.758194
6,2015-01-10 20:33:39,-73.983276,40.726009,-73.992470,40.749634
7,2015-01-10 20:33:39,-74.002663,40.734142,-73.995010,40.726326
8,2015-01-10 20:33:39,-73.783043,40.644356,-73.987595,40.759357
9,2015-01-10 20:33:40,-73.985588,40.767948,-73.985916,40.759365
10,2015-01-10 20:33:40,-73.988617,40.723103,-74.004395,40.728584
11,2015-01-10 20:33:41,-73.993782,40.751419,-73.967407,40.757217
12,2015-01-10 20:33:41,-74.008362,40.704376,-74.009773,40.707726
13,2015-01-10 20:33:41,-73.973946,40.760448,-73.997345,40.735210
14,2015-01-10 20:33:41,-74.006721,40.731777,-73.995216,40.739895
15,2015-01-15 19:05:39,-73.976425,40.739811,-73.983978,40.757889
16,2015-01-15 19:05:40,-73.968704,40.754246,-73.955124,40.786858
17,2015-01-15 19:05:40,-73.863060,40.769581,-73.952713,40.785782
18,2015-01-15 19:05:41,-73.945541,40.779423,-73.980850,40.786083
19,2015-01-15 19:05:41,-73.874458,40.774010,-73.952377,40.718590
20,2015-01-15 19:05:41,-73.976601,40.751896,-73.998924,40.714596
21,2015-01-15 19:05:41,-73.994957,40.745079,-73.999939,40.734650
22,2015-01-15 19:05:41,-74.000938,40.747063,-74.003563,40.735512
23,2015-01-15 19:05:41,-74.002777,40.717892,-74.007919,40.704220
24,2015-01-15 19:05:41,-73.997459,40.736362,-73.978172,40.761856
25,2015-01-15 19:05:41,-73.952278,40.823994,-73.953339,40.811089
26,2015-01-15 19:05:42,-73.991127,40.750080,-73.988609,40.734890
27,2015-01-15 19:05:42,-73.786575,40.644127,-73.985603,40.743530
28,2015-01-15 19:05:42,-73.993668,40.741447,-73.994514,40.757721
29,2015-01-15 19:05:42,-73.985291,40.744083,-74.009079,40.704689
...,...,...,...,...,...
12748956,2015-01-23 12:27:15,-73.958443,40.778362,-73.969795,40.764603
12748957,2015-01-23 12:27:15,-73.987335,40.768406,-73.998055,40.740685
12748958,2015-01-23 12:27:15,-73.954872,40.765572,-73.931190,40.767963
12748959,2015-01-23 12:27:15,-73.980652,40.759396,-73.992538,40.749332
12748960,2015-01-23 12:27:16,-73.992844,40.733875,-73.997375,40.727638
12748961,2015-01-23 12:27:16,-73.983971,40.749336,-73.986771,40.733913
12748962,2015-01-23 12:27:17,-73.990837,40.759426,-73.977943,40.789776
12748963,2015-01-23 12:27:17,-73.984108,40.780148,-73.956154,40.807259
12748964,2015-01-10 19:01:40,-74.006248,40.741375,-73.991386,40.738457
12748965,2015-01-10 19:01:40,-73.950005,40.772049,-73.991814,40.759243
12748966,2015-01-10 19:01:41,-73.952354,40.769779,-73.990189,40.730953
12748967,2015-01-10 19:01:41,-74.000916,40.762001,-73.971794,40.797024
12748968,2015-01-10 19:01:41,-73.976318,40.765816,-73.987381,40.775139
12748969,2015-01-10 19:01:41,-73.956383,40.767124,-73.982300,40.768372
12748970,2015-01-10 19:01:41,-73.984947,40.728088,-73.993469,40.727413
12748971,2015-01-10 19:01:42,-73.993622,40.728634,-74.000839,40.721409
12748972,2015-01-10 19:01:42,-73.964211,40.767441,-73.992050,40.755951
12748973,2015-01-10 19:01:42,-73.979729,40.763844,-73.990929,40.746349
12748974,2015-01-10 19:01:43,-73.993729,40.758690,-73.998039,40.736324
12748975,2015-01-10 19:01:43,-73.989044,40.730389,-73.971138,40.748104
12748976,2015-01-10 19:01:43,-73.981789,40.765335,-73.980782,40.744892
12748977,2015-01-10 19:01:43,-73.951477,40.785252,-73.996536,40.738205
12748978,2015-01-10 19:01:43,-73.984421,40.748260,-73.989220,40.730583
12748979,2015-01-10 19:01:43,-73.994240,40.750805,-73.988686,40.730900
12748980,2015-01-10 19:01:44,-73.980827,40.744530,-74.008873,40.740929
12748981,2015-01-10 19:01:44,-73.951988,40.786217,-73.953735,40.775162
12748982,2015-01-10 19:01:44,-73.982742,40.728184,-73.974976,40.720013
12748983,2015-01-10 19:01:44,-73.979324,40.749550,-73.969101,40.787800
12748984,2015-01-10 19:01:44,-73.999565,40.738483,-73.981819,40.737652
12748985,2015-01-10 19:01:45,-73.960350,40.766399,-73.968643,40.760777

In [3]:
dt=np.vstack(important_data.tpep_pickup_datetime.astype(str).apply(lambda x:list(map(str,[x[:10],x[11:13]]))).values)
important_data['date']=dt[:,0]
important_data['time']=dt[:,1]

In [4]:
important_data=important_data.drop(['tpep_pickup_datetime'],axis=1)
important_data

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,date,number,time
0,-73.993896,40.750111,-73.974785,40.750618,2015-01-15,15,19
1,-74.001648,40.724243,-73.994415,40.759109,2015-01-10,10,20
2,-73.963341,40.802788,-73.951820,40.824413,2015-01-10,10,20
3,-74.009087,40.713818,-74.004326,40.719986,2015-01-10,10,20
4,-73.971176,40.762428,-74.004181,40.742653,2015-01-10,10,20
5,-73.874374,40.774048,-73.986977,40.758194,2015-01-10,10,20
6,-73.983276,40.726009,-73.992470,40.749634,2015-01-10,10,20
7,-74.002663,40.734142,-73.995010,40.726326,2015-01-10,10,20
8,-73.783043,40.644356,-73.987595,40.759357,2015-01-10,10,20
9,-73.985588,40.767948,-73.985916,40.759365,2015-01-10,10,20
10,-73.988617,40.723103,-74.004395,40.728584,2015-01-10,10,20
11,-73.993782,40.751419,-73.967407,40.757217,2015-01-10,10,20
12,-74.008362,40.704376,-74.009773,40.707726,2015-01-10,10,20
13,-73.973946,40.760448,-73.997345,40.735210,2015-01-10,10,20
14,-74.006721,40.731777,-73.995216,40.739895,2015-01-10,10,20
15,-73.976425,40.739811,-73.983978,40.757889,2015-01-15,15,19
16,-73.968704,40.754246,-73.955124,40.786858,2015-01-15,15,19
17,-73.863060,40.769581,-73.952713,40.785782,2015-01-15,15,19
18,-73.945541,40.779423,-73.980850,40.786083,2015-01-15,15,19
19,-73.874458,40.774010,-73.952377,40.718590,2015-01-15,15,19
20,-73.976601,40.751896,-73.998924,40.714596,2015-01-15,15,19
21,-73.994957,40.745079,-73.999939,40.734650,2015-01-15,15,19
22,-74.000938,40.747063,-74.003563,40.735512,2015-01-15,15,19
23,-74.002777,40.717892,-74.007919,40.704220,2015-01-15,15,19
24,-73.997459,40.736362,-73.978172,40.761856,2015-01-15,15,19
25,-73.952278,40.823994,-73.953339,40.811089,2015-01-15,15,19
26,-73.991127,40.750080,-73.988609,40.734890,2015-01-15,15,19
27,-73.786575,40.644127,-73.985603,40.743530,2015-01-15,15,19
28,-73.993668,40.741447,-73.994514,40.757721,2015-01-15,15,19
29,-73.985291,40.744083,-74.009079,40.704689,2015-01-15,15,19
...,...,...,...,...,...,...,...
12748956,-73.958443,40.778362,-73.969795,40.764603,2015-01-23,23,12
12748957,-73.987335,40.768406,-73.998055,40.740685,2015-01-23,23,12
12748958,-73.954872,40.765572,-73.931190,40.767963,2015-01-23,23,12
12748959,-73.980652,40.759396,-73.992538,40.749332,2015-01-23,23,12
12748960,-73.992844,40.733875,-73.997375,40.727638,2015-01-23,23,12
12748961,-73.983971,40.749336,-73.986771,40.733913,2015-01-23,23,12
12748962,-73.990837,40.759426,-73.977943,40.789776,2015-01-23,23,12
12748963,-73.984108,40.780148,-73.956154,40.807259,2015-01-23,23,12
12748964,-74.006248,40.741375,-73.991386,40.738457,2015-01-10,10,19
12748965,-73.950005,40.772049,-73.991814,40.759243,2015-01-10,10,19
12748966,-73.952354,40.769779,-73.990189,40.730953,2015-01-10,10,19
12748967,-74.000916,40.762001,-73.971794,40.797024,2015-01-10,10,19
12748968,-73.976318,40.765816,-73.987381,40.775139,2015-01-10,10,19
12748969,-73.956383,40.767124,-73.982300,40.768372,2015-01-10,10,19
12748970,-73.984947,40.728088,-73.993469,40.727413,2015-01-10,10,19
12748971,-73.993622,40.728634,-74.000839,40.721409,2015-01-10,10,19
12748972,-73.964211,40.767441,-73.992050,40.755951,2015-01-10,10,19
12748973,-73.979729,40.763844,-73.990929,40.746349,2015-01-10,10,19
12748974,-73.993729,40.758690,-73.998039,40.736324,2015-01-10,10,19
12748975,-73.989044,40.730389,-73.971138,40.748104,2015-01-10,10,19
12748976,-73.981789,40.765335,-73.980782,40.744892,2015-01-10,10,19
12748977,-73.951477,40.785252,-73.996536,40.738205,2015-01-10,10,19
12748978,-73.984421,40.748260,-73.989220,40.730583,2015-01-10,10,19
12748979,-73.994240,40.750805,-73.988686,40.730900,2015-01-10,10,19
12748980,-73.980827,40.744530,-74.008873,40.740929,2015-01-10,10,19
12748981,-73.951988,40.786217,-73.953735,40.775162,2015-01-10,10,19
12748982,-73.982742,40.728184,-73.974976,40.720013,2015-01-10,10,19
12748983,-73.979324,40.749550,-73.969101,40.787800,2015-01-10,10,19
12748984,-73.999565,40.738483,-73.981819,40.737652,2015-01-10,10,19
12748985,-73.960350,40.766399,-73.968643,40.760777,2015-01-10,10,19

In [5]:
# important_data.drop(['number'],axis=1)
# result=important_data.groupby('date').groups

In [8]:
for name,group in important_data.groupby('date'):
    group.to_csv(name+'.csv',index=False)